### ISSUE TITLE
ImportError: cannot import name 'pyopenpose

### ISSUE THREAD

**Issue by saszer** [ortegatron/liveposetracker#6]
PS D:\liveposetracker-master\liveposetracker-master\src> python Twister.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "Twister.py", line 3, in <module>
    from Input import Input
  File "D:\liveposetracker-master\liveposetracker-master\src\Input.py", line 10, in <module>
    from openpose import pyopenpose as op
  File "D:\openpose-master\build\python\openpose\__init__.py", line 1, in <module>
    from . import pyopenpose as pyopenpose
ImportError: cannot import name 'pyopenpose'

**Comment by stan-lu** [comment]
Did you turn on the python flag cmake -DBUILD_PYTHON=ON .. before compiling OpenPose from your build directory?

**Comment by drushtig** [comment]
I am also stuck with the above error tried with turning on the python flag but still the issue is not resolved do let me know a solution.
