### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by chwongAI** [ortegatron/liveposetracker#7]
```
Traceback (most recent call last):
  File "Twister.py", line 35, in <module>
    game.run()
  File "Twister.py", line 22, in run
    self.input.run()
  File "/home/dev/Desktop/personTracking/liveposetracker-master/src/Input.py", line 74, in run
    poses = keypoints[:,:,:2]
IndexError: too many indices for array

Error occurred on a thread. OpenPose closed all its threads and then propagated the error to the main thread. Error description:

Prototxt file not found: /home/marcelo/openpose/models/pose/body_25/pose_deploy.prototxt.
Possible causes:
	1. Not downloading the OpenPose trained models.
	2. Not running OpenPose from the same directory where the `model` folder is located.
	3. Using paths with spaces.

```

Got this error when the program try to start stream via rstp. or play a mp4 file. 
And when I visit the directory, where it says not found, Im able to find 'pose_deploy.prototxt'

**Comment by stan-lu** [comment]
It seems like the "too many indices for array" error is caused when there are no keypoints detected by OpenPose, where keypoints is an empty array.
